name: Deploy npm app to GitHub Pages

on:
  push:
    branches:
      - main # This will trigger the workflow on pushes to the 'main' branch

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use your desired Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build npm app
        run: npm run build # Adjust this command if your build script is different

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # IMPORTANT: Change 'dist' to your actual build output directory

  # Deploy job
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4